const  {FIRESTORE_TEMPLATES_PATH,FIRESTORE_CATEGORIES_PATH,FIRESTORE_MEMES_PATH} = require("../../BuildConfig")
module.exports ={
    MIN_TEMPLATE_TITLE_LEN:3,
    MAX_TEMPLATE_TITLE_LEN:100,
    MIN_USERNAME_LEN:3,
    MAX_USERNAME_LEN:16,
    TEMPLATE_LIST_LIMIT:40,
    RECENT_MEMES_LIMIT:10,
    TEMPLATE_GROUP_LIMIT:50,
    SEARCH_TAGS_MAX_LENGTH:300,
    REPORT_USERS_COLLECTION_BATCH_SIZE:300,

    FAV_TEMPLATETYPE:"FAVORITES",
    REPORT_NOT_A_TEMPLATE:"Not a template",
    REPORT_SPAM:"SPAM",
    REPORT_INAPPROPRIATE:"INAPPROPRIATE",
    USER_STATUS_DEFAULT:"ACTIVE",
    USER_STATUS_BLOCKED:"BLOCKED",
    /*used to check whether the request from all templates category*/
    PREFIX_ALL:"ALL",
    UPDATE_MESSAGE:"Update app to continue",
    FIRESTORE_TEMPLATES_PATH,
    FIRESTORE_CATEGORIES_PATH,
    FIRESTORE_MEMES_PATH,
    ADMIN_FCM_TOPIC_ID:"FCM_MEME_KING_ADMIN",
    INSTA_USERNAME_APP_VERSION:50

}